[package]
name = "roboarm-sim"
version = "0.1.0"
authors = ["Daan de Graaf <daandegraaf9@gmail.com>"]

[dependencies]
nalgebra   = "0.16"
ncollide2d = "0.17"
nphysics2d = "0.9"
nphysics_testbed2d = "0.2"
